//import Logger from "../utils/logger.js";
import Logger from "../utils/logger.js";
const mode = process.env.MODE || "localhost";
Logger.debug(`Server is running in ${mode} mode`);

const configByEnv = {
  staging: {
    database: {
      HOST: "___.rds.amazonaws.com",
      USER: "admin",
      PORT: 3306,
      PASSWORD: process.env.PASSWORD,
      NAME: "koal-staging",
      dialect: "mysql",
      pool: {
        max: 5,
        min: 0,
        acquire: 30000,
        idle: 10000,
      },
    },
    port: process.env.PORT || 5000,
    allowedOrigins: "http://",
    TOKEN_KEY: process.env.TOKEN || "KOALY_KEY_LOCAL",
    confirmationCodeLimit: 10,
    tokenExpireDayLimit: 30,
    loggerDebounceAmountInMS: 60000,
    smsSiteID: 35749,
    smsSitePassword: process.env.SMSPASSWORD,
    smsSenderPhone: "KOALI_SITE",
    smsMessageInnerName: "koali_sms",
    allowedAmountOfRequestsForIpPerMinute: 600,
    allowedAmountOfRequestsForIpPerFullDay: 24 * 60 * 300,
    googlePhonenumber: "972111111111",
    gmailUserName: "_____.service@gmail.com",
    gmailPassword: process.env.GMAIL_PASSWORD,
    alertUtilUrl: "http://0.0.0.0:8089/updateAlerts/",
    passwordIncryptSalt: 10,
  },
  production: {
    database: {
      HOST: "___.rds.amazonaws.com",
      USER: "admin",
      PORT: 3306,
      PASSWORD: process.env.PASSWORD,
      NAME: "koal-staging",
      dialect: "mysql",
      pool: {
        max: 5,
        min: 0,
        acquire: 30000,
        idle: 10000,
      },
    },
    port: process.env.PORT || 5000,
    allowedOrigins: "http://",
    TOKEN_KEY: process.env.TOKEN || "KOALY_KEY_LOCAL",
    confirmationCodeLimit: 10,
    tokenExpireDayLimit: 30,
    loggerDebounceAmountInMS: 60000,
    smsSiteID: 35749,
    smsSitePassword: process.env.SMSPASSWORD,
    smsSenderPhone: "KOALI_SITE",
    smsMessageInnerName: "koali_sms",
    allowedAmountOfRequestsForIpPerMinute: 600,
    allowedAmountOfRequestsForIpPerFullDay: 24 * 60 * 300,
    googlePhonenumber: "972111111111",
    gmailUserName: "_____.service@gmail.com",
    gmailPassword: process.env.GMAIL_PASSWORD,
    alertUtilUrl: "http://0.0.0.0:8089/updateAlerts/",
    passwordIncryptSalt: 10,
  },
  localhost: {
    database: {
      HOST: "___.rds.amazonaws.com",
      USER: "admin",
      PORT: 3306,
      PASSWORD: process.env.PASSWORD,
      NAME: "koal-staging",
      dialect: "mysql",
      pool: {
        max: 5,
        min: 0,
        acquire: 30000,
        idle: 10000,
      },
    },
    port: process.env.PORT || 5000,
    allowedOrigins: "http://",
    TOKEN_KEY: process.env.TOKEN || "KOALY_KEY_LOCAL",
    confirmationCodeLimit: 10,
    tokenExpireDayLimit: 30,
    loggerDebounceAmountInMS: 60000,
    smsSiteID: 35749,
    smsSitePassword: process.env.SMSPASSWORD,
    smsSenderPhone: "KOALI_SITE",
    smsMessageInnerName: "koali_sms",
    allowedAmountOfRequestsForIpPerMinute: 600,
    allowedAmountOfRequestsForIpPerFullDay: 24 * 60 * 300,
    googlePhonenumber: "972111111111",
    gmailUserName: "_____.service@gmail.com",
    gmailPassword: process.env.GMAIL_PASSWORD,
    alertUtilUrl: "http://0.0.0.0:8089/updateAlerts/",
    passwordIncryptSalt: 10,
  },
};

export default configByEnv[mode];
